# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  docker: circleci/docker@1.0.1

workflows:
  build-and-publish-docker-image:
    jobs:
      - test
      - docker/publish:
          context: kramergroup-docker-public
          image: "kramergroup/traefik-forward-auth:<< pipeline.git.revision >>"

jobs:

  test:
    docker:
      - image: circleci/golang:1.13
    
    steps:
      - checkout
      - run: env GO111MODULE=on go get -v -t -d ./...
      - run: env GO111MODULE=on go test -v ./...


